# Generated by Django 5.1.3 on 2025-06-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('skills', models.TextField(help_text='Через запятую', verbose_name='Навыки')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт (годы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='team_works/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='team.teammember', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Работа участника',
                'verbose_name_plural': 'Работы участников',
                'ordering': ['-created_at'],
            },
        ),
    ]
