# Generated by Django 5.1.3 on 2025-06-15 10:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammemberwork',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team_works/', verbose_name='Изображение'),
        ),
    ]
