# Generated by Django 5.1.3 on 2025-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Изображение')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=200, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_at'],
            },
        ),
    ]
