# Generated by Django 5.2.4 on 2025-09-30 12:19

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testimonial_client_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='blog/', verbose_name='Изображение')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=200, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='VK')),
                ('skills', models.TextField(help_text='Через запятую', verbose_name='Навыки')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт (годы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team_works/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.teammember', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Работа участника',
                'verbose_name_plural': 'Работы участников',
                'ordering': ['-created_at'],
            },
        ),
    ]
