# Generated by Django 5.1.3 on 2025-06-15 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('avatar', models.ImageField(blank=True, upload_to='reviews/avatars/', verbose_name='Аватар')),
                ('rating', models.IntegerField(help_text='От 1 до 5 звезд', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('service_used', models.CharField(blank=True, max_length=200, verbose_name='Какую услугу использовали')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Рекомендуете ли нас?')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
