# Generated by Django 5.1.3 on 2025-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('gif', 'GIF')], max_length=10, verbose_name='Тип контента')),
                ('image', models.ImageField(blank=True, upload_to='fun/images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, upload_to='fun/videos/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Смешной контент',
                'verbose_name_plural': 'Смешной контент',
                'ordering': ['-created_at'],
            },
        ),
    ]
