# Generated by Django 5.2.4 on 2025-09-30 12:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcontent',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='fun/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='funcontent',
            name='video',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='fun/videos/', verbose_name='Видео файл'),
        ),
    ]
